### ISSUE TITLE
运行demo.py 时显存问题

### ISSUE THREAD

**Issue by weiweili123** [chineseocr/chinese-ocr#40]
2018-01-04 10:24:20.694079: E tensorflow/core/common_runtime/direct_session.cc:171] Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY; total memory reported: 8508014592
Traceback (most recent call last):
  File "demo.py", line 2, in <module>
    import model
  File "/home/zou/chinese-ocr-master/model.py", line 3, in <module>
    from ctpn.text_detect import text_detect
  File "/home/zou/chinese-ocr-master/ctpn/text_detect.py", line 1, in <module>
    from ctpn.model import ctpn
  File "/home/zou/chinese-ocr-master/ctpn/ctpn/model.py", line 29, in <module>
    sess,saver,net = load_tf_model()
  File "/home/zou/chinese-ocr-master/ctpn/ctpn/model.py", line 20, in load_tf_model
    sess = tf.Session(config=config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1486, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 621, in __init__
    self._session = tf_session.TF_NewDeprecatedSession(opts, status)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InternalError: Failed to create session.
博主您好！我在运行demo.py的时候出现了显存不足的问题，但是训练机上配置了2块1080，有16G显存，不知道代码应该怎样改？

**Comment by weiweili123** [comment]
而且在运行python crnn_main.py --cuda --adadelta时会出现
 batchSize=128, beta1=0.5, crnn='../pretrain-models/netCRNN.pth', cuda=True, displayInterval=50, experiment='./save_model', imgH=32, imgW=256, keep_ratio=False, lr=0.005, n_test_disp=1000, ngpu=1, nh=256, niter=1000000, random_sample=False, saveInterval=1000, trainroot='../data/lmdb/train', valInterval=50, valroot='../data/lmdb/val', workers=4)
mkdir: 无法创建目录"./save_model": 文件已存在
Random Seed:  2220
loading pretrained model from ../pretrain-models/netCRNN.pth
THCudaCheck FAIL file=/pytorch/torch/lib/THC/generic/THCStorage.c line=79 error=2 : out of memory
段错误 (核心已转储)

**Comment by weiweili123** [comment]
运行 sh train-keras.sh会出现
2018-01-04 10:35:40.992538: E tensorflow/core/common_runtime/direct_session.cc:171] Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY; total memory reported: 8508014592
Traceback (most recent call last):
  File "trainbatch.py", line 7, in <module>
    basemodel.load_weights(modelPath)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 2619, in load_weights
    load_weights_from_hdf5_group(f, self.layers)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 3095, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 2193, in batch_set_value
    get_session().run(assign_ops, feed_dict=feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 163, in get_session
    _SESSION = tf.Session(config=config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1486, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 621, in __init__
    self._session = tf_session.TF_NewDeprecatedSession(opts, status)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InternalError: Failed to create session.

**Comment by wenlihaoyu** [comment]
with tf.device('/gpu:0'): 调用指定显卡

**Comment by wenlihaoyu** [comment]
或者在文件抬头加入如下代码：
import os
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = "0"

**Comment by weiweili123** [comment]
谢谢博主！加入代码后问题已经解决。
![image](https://user-images.githubusercontent.com/35058025/34553070-7472c162-f160-11e7-9a33-7db7043f5537.png)
![image](https://user-images.githubusercontent.com/35058025/34553083-845d1848-f160-11e7-9272-e9e2d909f708.png)
测试的结果很不错。现在有两个问题想继续咨询博主：1、标点符号的识别效果非常好，里面用了什么策略吗？2、运行demo.py的时候处理一张图片的时间要6-8s，有没有什么方法可以加速？

**Comment by wenlihaoyu** [comment]
和训练样本构造的语料有关系，是爬取互联网上的新闻数据。GPU模式下的识别，大概就1秒内，不知道你为什么这么长的时间，CPU模式下差不多6-8S

**Comment by carterbao** [comment]
@weiweili123 可能你没有打开crnn.py中的GPU = True，（默认是GPU = False）所以用的是CPU mode在跑

**Comment by KyrieHee** [comment]
@weiweili123 
when I run demo.py
`Traceback (most recent call last):
  File "/home/tzb/work/OCR-ID/demo.py", line 2, in <module>
    import model
  File "/home/tzb/work/OCR-ID/model.py", line 3, in <module>
    from ctpn.text_detect import text_detect
  File "/home/tzb/work/OCR-ID/ctpn/text_detect.py", line 1, in <module>
    from ctpn.model import ctpn
ModuleNotFoundError: No module named 'ctpn.model'`
